require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  Exclude:
    - 'db/**/*'
    - 'script/**/*'
    - 'bin/**/*'

Metrics/LineLength:
  Exclude:
    - spec/**/*
    - config/**/*
  Max: 100

Metrics/BlockLength:
  Exclude:
    - config/**/*
    - spec/**/*

Lint/AmbiguousBlockAssociation:
  Exclude:
    - spec/**/*

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/BlockComments:
  Enabled: false

Style/GlobalStdStream:
  Enabled: false

RSpec/ImplicitExpect:
  Enabled: false

Rails/FilePath:
  Exclude:
    - spec/**/*

RSpec/MultipleExpectations:
  Exclude:
    - spec/features/**/*

RSpec/ExampleLength:
  Exclude:
    - spec/**/*

RSpec/MultipleMemoizedHelpers:
  Exclude:
    - spec/**/*